
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-4
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-Zipcode","number":22,"title":"Add ZipCode Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-4/pull/22"},{"author":{"id":"U_kgDOB7tbUw","is_bot":false,"login":"Torry051","name":"Rui Tong"},"headRefName":"Torry-JokeQuery","number":20,"title":"Add Joke Query Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-4/pull/20"},{"author":{"id":"U_kgDOBXuxxw","is_bot":false,"login":"Cory-Zhao","name":"Cory Zhao"},"headRefName":"Cory-Tides","number":19,"title":"Add Tides Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-4/pull/19"},{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-ZipCodeQueryService","number":18,"title":"Add ZipCodeQueryService and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-4/pull/18"}]
