
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-4
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOBdHvhQ","is_bot":false,"login":"anirudhiyer1","name":""},"headRefName":"AnirudhLocationController","number":29,"title":"Anirudh location controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-4/pull/29"},{"author":{"id":"U_kgDOBdHvhQ","is_bot":false,"login":"anirudhiyer1","name":""},"headRefName":"Anirudh-LocationService","number":28,"title":"Anirudh location service","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-4/pull/28"}]
